package os.proximity.shared.storage

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * [AtRestCipher] backed by an AES-256-GCM key generated inside the Android
 * Keystore and never exported.
 *
 * This is why [AtRestCipher] takes no raw key bytes: on a device with a TEE
 * or StrongBox, this key's material never exists outside secure hardware,
 * at any point — not wrapped, not reconstructed in process memory, at all.
 * That is a materially different guarantee from wrapping a software key
 * with a Keystore key (the approach ADR 0001 rejected for identity, for the
 * same reason), and the same reasoning applies here: the data this cipher
 * protects — the audit log, trust decisions, file drops — deserves the
 * strongest available guarantee, not the cheapest one that still counts as
 * "encrypted."
 *
 * Not unit-testable outside a real device or emulator, same as
 * [os.proximity.shared.identity.KeystoreDeviceIdentityProvider] — Android
 * Keystore is unavailable to a plain JVM test.
 * [os.proximity.shared.storage.EncryptedFileStoreTest] covers the
 * record-format logic this class's seal/open methods slot into, using a
 * plain-JVM stand-in cipher.
 */
class AndroidKeystoreAtRestCipher : AtRestCipher {

    private val secretKey: SecretKey by lazy { loadOrCreateKey() }

    override fun seal(aad: ByteArray, plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        cipher.updateAAD(aad)
        val ciphertext = cipher.doFinal(plaintext)
        // GCM's IV is generated internally when the Keystore provider is
        // left to pick it (required for a Keystore-backed key, which will
        // not accept an application-supplied IV) — so, unlike the app's own
        // AndroidCryptoPrimitives, it must be read back out here rather
        // than generated by the caller.
        return cipher.iv + ciphertext
    }

    override fun open(aad: ByteArray, sealed: ByteArray): ByteArray? {
        if (sealed.size < GCM_IV_SIZE) return null
        return try {
            val iv = sealed.copyOfRange(0, GCM_IV_SIZE)
            val ciphertext = sealed.copyOfRange(GCM_IV_SIZE, sealed.size)
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey, GCMParameterSpec(GCM_TAG_BITS, iv))
            cipher.updateAAD(aad)
            cipher.doFinal(ciphertext)
        } catch (e: Exception) {
            // Authentication failure, a key from a wiped-and-regenerated
            // keystore, or corrupt input — all read the same to a caller:
            // this record cannot be recovered.
            null
        }
    }

    private fun loadOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "kodama_at_rest_key_v1"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_SIZE = 12
        private const val GCM_TAG_BITS = 128
    }
}
